/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: chat_application.proto */

#ifndef PROTOBUF_C_chat_5fapplication_2eproto__INCLUDED
#define PROTOBUF_C_chat_5fapplication_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct Authentication Authentication;
typedef struct AuthAndIdCheckReply AuthAndIdCheckReply;
typedef struct ExchangeMessage ExchangeMessage;
typedef struct ChatEnvelope ChatEnvelope;


/* --- enums --- */


/* --- messages --- */

struct  Authentication
{
  ProtobufCMessage base;
  char *request_type;
  char *username;
  char *password;
};
#define AUTHENTICATION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&authentication__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


struct  AuthAndIdCheckReply
{
  ProtobufCMessage base;
  char *text;
};
#define AUTH_AND_ID_CHECK_REPLY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&auth_and_id_check_reply__descriptor) \
    , (char *)protobuf_c_empty_string }


struct  ExchangeMessage
{
  ProtobufCMessage base;
  char *message_type;
  char *sender;
  char *receiver;
  char *conversation;
};
#define EXCHANGE_MESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&exchange_message__descriptor) \
    , (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


typedef enum {
  CHAT_ENVELOPE__PAYLOAD__NOT_SET = 0,
  CHAT_ENVELOPE__PAYLOAD_AUTH = 1,
  CHAT_ENVELOPE__PAYLOAD_EXCHANGEMSG = 2,
  CHAT_ENVELOPE__PAYLOAD_AUTHANDIDCHECKREPLY = 3
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(CHAT_ENVELOPE__PAYLOAD__CASE)
} ChatEnvelope__PayloadCase;

struct  ChatEnvelope
{
  ProtobufCMessage base;
  ChatEnvelope__PayloadCase payload_case;
  union {
    Authentication *auth;
    ExchangeMessage *exchangemsg;
    AuthAndIdCheckReply *authandidcheckreply;
  };
};
#define CHAT_ENVELOPE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&chat_envelope__descriptor) \
    , CHAT_ENVELOPE__PAYLOAD__NOT_SET, {0} }


/* Authentication methods */
void   authentication__init
                     (Authentication         *message);
size_t authentication__get_packed_size
                     (const Authentication   *message);
size_t authentication__pack
                     (const Authentication   *message,
                      uint8_t             *out);
size_t authentication__pack_to_buffer
                     (const Authentication   *message,
                      ProtobufCBuffer     *buffer);
Authentication *
       authentication__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   authentication__free_unpacked
                     (Authentication *message,
                      ProtobufCAllocator *allocator);
/* AuthAndIdCheckReply methods */
void   auth_and_id_check_reply__init
                     (AuthAndIdCheckReply         *message);
size_t auth_and_id_check_reply__get_packed_size
                     (const AuthAndIdCheckReply   *message);
size_t auth_and_id_check_reply__pack
                     (const AuthAndIdCheckReply   *message,
                      uint8_t             *out);
size_t auth_and_id_check_reply__pack_to_buffer
                     (const AuthAndIdCheckReply   *message,
                      ProtobufCBuffer     *buffer);
AuthAndIdCheckReply *
       auth_and_id_check_reply__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   auth_and_id_check_reply__free_unpacked
                     (AuthAndIdCheckReply *message,
                      ProtobufCAllocator *allocator);
/* ExchangeMessage methods */
void   exchange_message__init
                     (ExchangeMessage         *message);
size_t exchange_message__get_packed_size
                     (const ExchangeMessage   *message);
size_t exchange_message__pack
                     (const ExchangeMessage   *message,
                      uint8_t             *out);
size_t exchange_message__pack_to_buffer
                     (const ExchangeMessage   *message,
                      ProtobufCBuffer     *buffer);
ExchangeMessage *
       exchange_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   exchange_message__free_unpacked
                     (ExchangeMessage *message,
                      ProtobufCAllocator *allocator);
/* ChatEnvelope methods */
void   chat_envelope__init
                     (ChatEnvelope         *message);
size_t chat_envelope__get_packed_size
                     (const ChatEnvelope   *message);
size_t chat_envelope__pack
                     (const ChatEnvelope   *message,
                      uint8_t             *out);
size_t chat_envelope__pack_to_buffer
                     (const ChatEnvelope   *message,
                      ProtobufCBuffer     *buffer);
ChatEnvelope *
       chat_envelope__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   chat_envelope__free_unpacked
                     (ChatEnvelope *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Authentication_Closure)
                 (const Authentication *message,
                  void *closure_data);
typedef void (*AuthAndIdCheckReply_Closure)
                 (const AuthAndIdCheckReply *message,
                  void *closure_data);
typedef void (*ExchangeMessage_Closure)
                 (const ExchangeMessage *message,
                  void *closure_data);
typedef void (*ChatEnvelope_Closure)
                 (const ChatEnvelope *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor authentication__descriptor;
extern const ProtobufCMessageDescriptor auth_and_id_check_reply__descriptor;
extern const ProtobufCMessageDescriptor exchange_message__descriptor;
extern const ProtobufCMessageDescriptor chat_envelope__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_chat_5fapplication_2eproto__INCLUDED */
