/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: chat_application.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "chat_application.pb-c.h"
void   authentication__init
                     (Authentication         *message)
{
  static const Authentication init_value = AUTHENTICATION__INIT;
  *message = init_value;
}
size_t authentication__get_packed_size
                     (const Authentication *message)
{
  assert(message->base.descriptor == &authentication__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t authentication__pack
                     (const Authentication *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &authentication__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t authentication__pack_to_buffer
                     (const Authentication *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &authentication__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Authentication *
       authentication__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Authentication *)
     protobuf_c_message_unpack (&authentication__descriptor,
                                allocator, len, data);
}
void   authentication__free_unpacked
                     (Authentication *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &authentication__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   auth_and_id_check_reply__init
                     (AuthAndIdCheckReply         *message)
{
  static const AuthAndIdCheckReply init_value = AUTH_AND_ID_CHECK_REPLY__INIT;
  *message = init_value;
}
size_t auth_and_id_check_reply__get_packed_size
                     (const AuthAndIdCheckReply *message)
{
  assert(message->base.descriptor == &auth_and_id_check_reply__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t auth_and_id_check_reply__pack
                     (const AuthAndIdCheckReply *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &auth_and_id_check_reply__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t auth_and_id_check_reply__pack_to_buffer
                     (const AuthAndIdCheckReply *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &auth_and_id_check_reply__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
AuthAndIdCheckReply *
       auth_and_id_check_reply__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (AuthAndIdCheckReply *)
     protobuf_c_message_unpack (&auth_and_id_check_reply__descriptor,
                                allocator, len, data);
}
void   auth_and_id_check_reply__free_unpacked
                     (AuthAndIdCheckReply *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &auth_and_id_check_reply__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   exchange_message__init
                     (ExchangeMessage         *message)
{
  static const ExchangeMessage init_value = EXCHANGE_MESSAGE__INIT;
  *message = init_value;
}
size_t exchange_message__get_packed_size
                     (const ExchangeMessage *message)
{
  assert(message->base.descriptor == &exchange_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t exchange_message__pack
                     (const ExchangeMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &exchange_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t exchange_message__pack_to_buffer
                     (const ExchangeMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &exchange_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ExchangeMessage *
       exchange_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ExchangeMessage *)
     protobuf_c_message_unpack (&exchange_message__descriptor,
                                allocator, len, data);
}
void   exchange_message__free_unpacked
                     (ExchangeMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &exchange_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   chat_envelope__init
                     (ChatEnvelope         *message)
{
  static const ChatEnvelope init_value = CHAT_ENVELOPE__INIT;
  *message = init_value;
}
size_t chat_envelope__get_packed_size
                     (const ChatEnvelope *message)
{
  assert(message->base.descriptor == &chat_envelope__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t chat_envelope__pack
                     (const ChatEnvelope *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &chat_envelope__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t chat_envelope__pack_to_buffer
                     (const ChatEnvelope *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &chat_envelope__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
ChatEnvelope *
       chat_envelope__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (ChatEnvelope *)
     protobuf_c_message_unpack (&chat_envelope__descriptor,
                                allocator, len, data);
}
void   chat_envelope__free_unpacked
                     (ChatEnvelope *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &chat_envelope__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor authentication__field_descriptors[3] =
{
  {
    "request_type",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Authentication, request_type),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "username",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Authentication, username),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "password",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Authentication, password),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned authentication__field_indices_by_name[] = {
  2,   /* field[2] = password */
  0,   /* field[0] = request_type */
  1,   /* field[1] = username */
};
static const ProtobufCIntRange authentication__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor authentication__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Authentication",
  "Authentication",
  "Authentication",
  "",
  sizeof(Authentication),
  3,
  authentication__field_descriptors,
  authentication__field_indices_by_name,
  1,  authentication__number_ranges,
  (ProtobufCMessageInit) authentication__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor auth_and_id_check_reply__field_descriptors[1] =
{
  {
    "text",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(AuthAndIdCheckReply, text),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned auth_and_id_check_reply__field_indices_by_name[] = {
  0,   /* field[0] = text */
};
static const ProtobufCIntRange auth_and_id_check_reply__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor auth_and_id_check_reply__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "AuthAndIdCheckReply",
  "AuthAndIdCheckReply",
  "AuthAndIdCheckReply",
  "",
  sizeof(AuthAndIdCheckReply),
  1,
  auth_and_id_check_reply__field_descriptors,
  auth_and_id_check_reply__field_indices_by_name,
  1,  auth_and_id_check_reply__number_ranges,
  (ProtobufCMessageInit) auth_and_id_check_reply__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor exchange_message__field_descriptors[4] =
{
  {
    "message_type",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ExchangeMessage, message_type),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sender",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ExchangeMessage, sender),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "receiver",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ExchangeMessage, receiver),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "conversation",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(ExchangeMessage, conversation),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned exchange_message__field_indices_by_name[] = {
  3,   /* field[3] = conversation */
  0,   /* field[0] = message_type */
  2,   /* field[2] = receiver */
  1,   /* field[1] = sender */
};
static const ProtobufCIntRange exchange_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor exchange_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ExchangeMessage",
  "ExchangeMessage",
  "ExchangeMessage",
  "",
  sizeof(ExchangeMessage),
  4,
  exchange_message__field_descriptors,
  exchange_message__field_indices_by_name,
  1,  exchange_message__number_ranges,
  (ProtobufCMessageInit) exchange_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor chat_envelope__field_descriptors[3] =
{
  {
    "auth",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ChatEnvelope, payload_case),
    offsetof(ChatEnvelope, auth),
    &authentication__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "exchangemsg",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ChatEnvelope, payload_case),
    offsetof(ChatEnvelope, exchangemsg),
    &exchange_message__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "authandidcheckreply",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(ChatEnvelope, payload_case),
    offsetof(ChatEnvelope, authandidcheckreply),
    &auth_and_id_check_reply__descriptor,
    NULL,
    0 | PROTOBUF_C_FIELD_FLAG_ONEOF,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned chat_envelope__field_indices_by_name[] = {
  0,   /* field[0] = auth */
  2,   /* field[2] = authandidcheckreply */
  1,   /* field[1] = exchangemsg */
};
static const ProtobufCIntRange chat_envelope__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor chat_envelope__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "ChatEnvelope",
  "ChatEnvelope",
  "ChatEnvelope",
  "",
  sizeof(ChatEnvelope),
  3,
  chat_envelope__field_descriptors,
  chat_envelope__field_indices_by_name,
  1,  chat_envelope__number_ranges,
  (ProtobufCMessageInit) chat_envelope__init,
  NULL,NULL,NULL    /* reserved[123] */
};
