/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: chat_application.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "chat_application.pb-c.h"
void   authentication__init
                     (Authentication         *message)
{
  static const Authentication init_value = AUTHENTICATION__INIT;
  *message = init_value;
}
size_t authentication__get_packed_size
                     (const Authentication *message)
{
  assert(message->base.descriptor == &authentication__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t authentication__pack
                     (const Authentication *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &authentication__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t authentication__pack_to_buffer
                     (const Authentication *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &authentication__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Authentication *
       authentication__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Authentication *)
     protobuf_c_message_unpack (&authentication__descriptor,
                                allocator, len, data);
}
void   authentication__free_unpacked
                     (Authentication *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &authentication__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   authentication_reply__init
                     (AuthenticationReply         *message)
{
  static const AuthenticationReply init_value = AUTHENTICATION_REPLY__INIT;
  *message = init_value;
}
size_t authentication_reply__get_packed_size
                     (const AuthenticationReply *message)
{
  assert(message->base.descriptor == &authentication_reply__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t authentication_reply__pack
                     (const AuthenticationReply *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &authentication_reply__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t authentication_reply__pack_to_buffer
                     (const AuthenticationReply *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &authentication_reply__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
AuthenticationReply *
       authentication_reply__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (AuthenticationReply *)
     protobuf_c_message_unpack (&authentication_reply__descriptor,
                                allocator, len, data);
}
void   authentication_reply__free_unpacked
                     (AuthenticationReply *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &authentication_reply__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor authentication__field_descriptors[3] =
{
  {
    "request_type",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Authentication, request_type),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "username",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Authentication, username),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "password",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Authentication, password),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned authentication__field_indices_by_name[] = {
  2,   /* field[2] = password */
  0,   /* field[0] = request_type */
  1,   /* field[1] = username */
};
static const ProtobufCIntRange authentication__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor authentication__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Authentication",
  "Authentication",
  "Authentication",
  "",
  sizeof(Authentication),
  3,
  authentication__field_descriptors,
  authentication__field_indices_by_name,
  1,  authentication__number_ranges,
  (ProtobufCMessageInit) authentication__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor authentication_reply__field_descriptors[1] =
{
  {
    "text",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(AuthenticationReply, text),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned authentication_reply__field_indices_by_name[] = {
  0,   /* field[0] = text */
};
static const ProtobufCIntRange authentication_reply__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor authentication_reply__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "AuthenticationReply",
  "AuthenticationReply",
  "AuthenticationReply",
  "",
  sizeof(AuthenticationReply),
  1,
  authentication_reply__field_descriptors,
  authentication_reply__field_indices_by_name,
  1,  authentication_reply__number_ranges,
  (ProtobufCMessageInit) authentication_reply__init,
  NULL,NULL,NULL    /* reserved[123] */
};
