%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.21.7

-ifndef(chat_application_pb).
-define(chat_application_pb, true).

-define(chat_application_pb_gpb_version, "4.21.7").


-ifndef('AUTHENTICATION_PB_H').
-define('AUTHENTICATION_PB_H', true).
-record('Authentication',
        {request_type = []      :: unicode:chardata() | undefined, % = 1, optional
         username = []          :: unicode:chardata() | undefined, % = 2, optional
         password = []          :: unicode:chardata() | undefined % = 3, optional
        }).
-endif.

-ifndef('AUTHENTICATIONREPLY_PB_H').
-define('AUTHENTICATIONREPLY_PB_H', true).
-record('AuthenticationReply',
        {text = []              :: unicode:chardata() | undefined % = 1, optional
        }).
-endif.

-endif.
