%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.21.7

-ifndef(chat_application).
-define(chat_application, true).

-define(chat_application_gpb_version, "4.21.7").


-ifndef('AUTHENTICATION_PB_H').
-define('AUTHENTICATION_PB_H', true).
-record('Authentication',
        {request_type = []      :: unicode:chardata() | undefined, % = 1, optional
         username = []          :: unicode:chardata() | undefined, % = 2, optional
         password = []          :: unicode:chardata() | undefined % = 3, optional
        }).
-endif.

-ifndef('AUTHENTICATIONREPLY_PB_H').
-define('AUTHENTICATIONREPLY_PB_H', true).
-record('AuthenticationReply',
        {text = []              :: unicode:chardata() | undefined % = 1, optional
        }).
-endif.

-ifndef('EXCHANGEMESSAGE_PB_H').
-define('EXCHANGEMESSAGE_PB_H', true).
-record('ExchangeMessage',
        {message_type = []      :: unicode:chardata() | undefined, % = 1, optional
         sender = []            :: unicode:chardata() | undefined, % = 2, optional
         receiver = []          :: unicode:chardata() | undefined, % = 3, optional
         conversation = []      :: unicode:chardata() | undefined % = 4, optional
        }).
-endif.

-ifndef('CHATENVELOPE_PB_H').
-define('CHATENVELOPE_PB_H', true).
-record('ChatEnvelope',
        {payload                :: {auth, chat_application:'Authentication'()} | {exchangemsg, chat_application:'ExchangeMessage'()} | undefined % oneof
        }).
-endif.

-endif.
